import Head from 'next/head'
import { useRouter } from 'next/router'

export default function Title() {
    const router = useRouter();


    const pageTitle = router.query.title; 


return (
    <>
    <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
    </Head>
    </>
)
}
